### ISSUE TITLE
Saving solution adds unwanted settings

### ISSUE THREAD

**Issue by rprouse** [SLaks/Rebracer#11]
### Scenario 1
1. Right click on solution, add new Rebracer.xml
2. Open Rebracer.xml and remove items that you don't want set with the solution, save.
3. Close the solution or hit Save All.

**Expected:** Rebracer.xml is not changed
**Actual:** Rebracer.xml is populated with all the settings it supports.
### Scenario 2
1. Open a solution with a Rebracer.xml file that has been pared down.
2. Edit your Visual Studio options, even one that is not supported by Rebracer. In my case it was debugging settings.

**Expected:** Rebracer.xml is not changed
**Actual:** Rebracer.xml is populated with all the settings it supports.
### Why this is a problem

Many of the options that Rebracer adds are not formatting related, but have to do with the behavior of Intellisense, Outlining, etc. Changing settings like this will just annoy other developers on the team. I might like my files to open with outlining collapsed, but other people might prefer it otherwise. I should not be dictating those options to other developers.

**Comment by CADbloke** [comment]
I found a few more - see attached zip of a diff report between your ReBracer.xml and the one my VS2015 + R# generated. I will try to arrange a PR. I will also try to look into tabs and spaces as per my gist at https://gist.github.com/CADbloke/6206b1d4084a88473689

"Try"

html diff report
[ReBracerExtras.zip](https://github.com/SLaks/Rebracer/files/91477/ReBracerExtras.zip)
