### ISSUE TITLE
CSharp section is not known to Rebracer

### ISSUE THREAD

**Issue by PetroProtsyk** [SLaks/Rebracer#14]
I've noticed that by default rebracer does not know about "CSharp" section in TextEditor settings. It only knows about "CSharp-Specific".

However there are some important settings in "CSharp" section as well. Such as:
 - TabSize
 - InsertTabs
etc.

Is there are a reasong why "CSharp" section is not in the default list of known settings?

Do you have plans to externalize the list of settings that will be persisted?

**Comment by SLaks** [comment]
This is deliberate.

To control indentation settings, you should use [EditorConfig](http://editorconfig.org/), which is fully cross-platform, and lets you specify different settings for specific file patterns.

You can find it in the Extension Gallery.
