### ISSUE TITLE
Doesn't seem to work with VS 2015

### ISSUE THREAD

**Issue by aloneguid** [SLaks/Rebracer#19]
Doesn't save tab/space settings, the rebracer.xml just doesn't have them.

**Comment by SLaks** [comment]
As mentioned in the README, Rebracer is not intended to save indentation settings,
Instead, use [EditorConfig](https://visualstudiogallery.msdn.microsoft.com/c8bccfe2-650c-4b42-bc5c-845e21f96328), which is far more flexible and works in every editor.

If you really want to save indentation settings in Rebracer, see https://gist.github.com/CADbloke/6206b1d4084a88473689
