### ISSUE TITLE
There is no "Rebracer settings file" option to add to my solution when I attempt to add a new file.

### ISSUE THREAD

**Issue by ekolis** [SLaks/Rebracer#25]
I'm trying to get started with Rebracer, and the instructions say to create an XML settings file, but that option doesn't exist on the "new file" dialog. I do have the extension installed and enabled.

**Comment by SLaks** [comment]
It's not a template (since it has a fixed name).
It's a menu item in the Add menu when you right-click the solution itself.

**Comment by ekolis** [comment]
Oh, thanks, I'm an idiot and forgot to look directly on the menu!
